### PR TITLE
Fix dropping of port for commands other than login

### PR DESCRIPTION
**Pull request by Martin4Kansas**
This fixes issue #10

### CODE REVIEW

**Comment by Martin4Kansas** [comment]
The basic issue with the existing code is that after making the initial login command, subsequent API calls don't have a port specified and therefore default to port 443.  If your API port is not 443, then every command other than login will always fail as it tries to communicate with the wrong port.

**Comment by Martin4Kansas** [comment]
@chkp-rdecker, when you get a chance please review this as I'm sure many others will have the same problem if they don't use port 443.

**Review by chkp-rdecker — CHANGES_REQUESTED** [review]
in the first if statement the argument of is_int method is incorrect - session_data["url"].split('/')[0].split(':')[1]
please review.

**Comment by Martin4Kansas** [comment]
@chkp-rdecker Good catch, fixed it.

**Review by chkp-rdecker — APPROVED** [review]

**Pull request merged**
