### PR TITLE
Replace 'None' with 'null' values in parameters

### PR DESCRIPTION
**Pull request by methadata**
As an hygienic measure, replace all null values in Ansible format (i.e. "None" values) with "null" values, that Python understands.

### CODE REVIEW

**Comment by Martin4Kansas** [comment]
What problem does this fix?  Does the use of "None" cause any errors that you're aware of?

**Comment by methadata** [comment]
AFAIK, using the (standard) keyword "None" in the parameters in this module crashes its execution. 
With the patch, Ansible's "None" is replaced by Python's "null", allowing the user to use a more standard Ansible syntax.

**Comment by chkp-rdecker** [comment]
Looks and works ok.
Please note that the null value in yml must be **without** quotes:
_snmp: null_

**Review by chkp-rdecker — APPROVED** [review]

**Comment by jordanmartinksu** [comment]
This change has already broken things for me on login.

 `fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_JFWOeS/ansible_module_check_point_mgmt.py\", line 248, in <module>\r\n    main()\r\n  File \"/tmp/ansible_JFWOeS/ansible_module_check_point_mgmt.py\", line 129, in main\r\n    parameters = parameters.replace(\"None\", \"null\")\r\nAttributeError: 'dict' object has no attribute 'replace'\r\n", "msg": "MODULE FAILURE", "rc": 0}`

**Comment by nbo32** [comment]
Could you tell us which Python version you are using please ?

**Comment by jordanmartinksu** [comment]
2.7.12

**Pull request merged**
